services:
# databases
  auth-db:
    image: postgres
    restart: always
    env_file:
      - ./auth_service/login_service/.env
    ports:
      - "5432:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

  todo-db:
    image: postgres
    restart: always
    env_file:
      - ./todo_service/clear_service/.env
    ports:
      - "5433:5432"
    volumes:
      - todo_pgdata:/var/lib/postgresql/data

# auth services
  signup-service:
    build: ./auth_service/signup_service
    ports:
      - "8001:8000"
    depends_on:
      - auth-db

  login-service:
    build: ./auth_service/login_service
    ports:
      - "8002:8000"
    depends_on:
      - auth-db

  validate-service:
    build: ./auth_service/validate_service
    ports:
      - "8003:8000"
    depends_on:
      - auth-db

# todo services
  todo-clear-service:
    build: ./todo_service/clear_service
    ports:
      - "8008:8000"
    depends_on:
      - todo-db

  todo-create-service:
    build: ./todo_service/create_service
    ports:
      - "8005:8000"
    depends_on:
      - todo-db

  todo-delete-service:
    build: ./todo_service/delete_service
    ports:
      - "8007:8000"
    depends_on:
      - todo-db

  todo-read-service:
    build: ./todo_service/read_service
    ports:
      - "8004:8000"
    depends_on:
      - todo-db

  todo-update-service:
    build: ./todo_service/update_service
    ports:
      - "8006:8000"
    depends_on:
      - todo-db



volumes:
  auth_pgdata:
  todo_pgdata:
