version: '3.9'

services:
  auth-db:
    image: postgres
    restart: always
    env_file:
      - ./auth_service/.env
    ports:
      - "5432:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

  auth-service:
    build: ./auth_service
    depends_on:
      - auth-db
    env_file:
      - ./auth_service/.env
    ports:
      - "8000:8000"
    volumes:
      - ./auth_service:/app

volumes:
  auth_pgdata:
